language: python
python:
 - "2.6"
 - "2.7"
# command to run tests
script:
 - python -n 250 ipcalc.py
 - python ipcalc.py 192.168.0.0/24
 - python -p ipcalc.py 10.15.6.1/27
 - python ipcac.py 172.16.0.0 255.248.0.0